/**
 * Beach content — AI-generated narrative content per beach.
 *
 * Stored in the `beach_content` Supabase table, regenerated by
 * `scripts/generate-beach-content.ts`. Hand-defined here rather than
 * regenerated through the Supabase type pipeline so the script and
 * application can evolve independently.
 */

export type BeachFaqIntent =
  | "family"
  | "swimming"
  | "parking"
  | "access"
  | "best-time"
  | "blue-flag"
  | "snorkeling"
  | "surfing"
  | "crowds"
  | "photography"
  | "distinctive-feature"
  | "water-quality"
  | "food-and-drink";

export interface BeachFaq {
  question: string;
  answer: string;
  intent: BeachFaqIntent;
  target_keywords: string[];
}

export interface BeachContent {
  beach_id: string;
  overview: string;
  amenities_summary: string | null;
  faqs: BeachFaq[];
  keywords: string[];
  generated_at: string;
  generator: string;
  prompt_version: string;
  human_edited: boolean;
  updated_at: string;
}

/**
 * Shape returned by the LLM, validated before insertion. Excludes the
 * metadata fields that the script populates server-side.
 */
export interface GeneratedBeachContent {
  overview: string;
  amenities_summary: string | null;
  faqs: BeachFaq[];
  keywords: string[];
}
