#!/usr/bin/env tsx

/**
 * Schema Validation Script for Structured Data
 *
 * Validates all JSON-LD schemas generated by the structured-data.ts module
 * to ensure they comply with Schema.org standards and best practices.
 *
 * Checks:
 * - No undefined/null values
 * - All URLs are absolute
 * - Dates are ISO 8601 format
 * - Required fields are present
 * - @context and @type are correct
 *
 * Usage:
 *   npm run validate:schemas
 *   or
 *   tsx scripts/validate-schemas.ts
 */

// File system imports removed - not used in this script

interface ValidationError {
  field: string;
  message: string;
  value?: unknown;
}

interface ValidationResult {
  isValid: boolean;
  errors: ValidationError[];
}

/**
 * Recursively check for undefined or null values in an object
 */
function checkForUndefinedOrNull(obj: unknown, path = ''): ValidationError[] {
  const errors: ValidationError[] = [];

  if (obj === undefined || obj === null) {
    errors.push({
      field: path || 'root',
      message: `Found ${obj === undefined ? 'undefined' : 'null'} value`,
      value: obj,
    });
    return errors;
  }

  if (typeof obj !== 'object' || Array.isArray(obj)) {
    if (Array.isArray(obj)) {
      obj.forEach((item, index) => {
        errors.push(...checkForUndefinedOrNull(item, `${path}[${index}]`));
      });
    }
    return errors;
  }

  for (const [key, value] of Object.entries(obj)) {
    const currentPath = path ? `${path}.${key}` : key;
    
    if (value === undefined || value === null) {
      errors.push({
        field: currentPath,
        message: `Found ${value === undefined ? 'undefined' : 'null'} value`,
        value,
      });
    } else if (typeof value === 'object' && !Array.isArray(value)) {
      errors.push(...checkForUndefinedOrNull(value, currentPath));
    } else if (Array.isArray(value)) {
      value.forEach((item, index) => {
        errors.push(...checkForUndefinedOrNull(item, `${currentPath}[${index}]`));
      });
    }
  }

  return errors;
}

/**
 * Check if a URL is absolute
 */
function isAbsoluteUrl(url: string): boolean {
  try {
    const parsed = new URL(url);
    return parsed.protocol === 'http:' || parsed.protocol === 'https:';
  } catch {
    return false;
  }
}

/**
 * Check if a date string is in ISO 8601 format (YYYY-MM-DD)
 */
function isISO8601Date(dateString: string): boolean {
  const iso8601Regex = /^\d{4}-\d{2}-\d{2}$/;
  return iso8601Regex.test(dateString);
}

/**
 * Recursively check URLs in an object
 */
function checkUrls(obj: unknown, path = ''): ValidationError[] {
  const errors: ValidationError[] = [];

  if (typeof obj !== 'object' || obj === null) {
    return errors;
  }

  if (Array.isArray(obj)) {
    obj.forEach((item, index) => {
      errors.push(...checkUrls(item, `${path}[${index}]`));
    });
    return errors;
  }

  for (const [key, value] of Object.entries(obj)) {
    const currentPath = path ? `${path}.${key}` : key;

    if (key === 'url' || key === '@id' || (key === 'item' && typeof value === 'string')) {
      if (typeof value === 'string' && !isAbsoluteUrl(value)) {
        errors.push({
          field: currentPath,
          message: 'URL must be absolute (start with http:// or https://)',
          value,
        });
      }
    } else if (key === 'datePublished' || key === 'dateModified') {
      if (typeof value === 'string' && !isISO8601Date(value)) {
        errors.push({
          field: currentPath,
          message: 'Date must be in ISO 8601 format (YYYY-MM-DD)',
          value,
        });
      }
    } else if (typeof value === 'object' && value !== null) {
      errors.push(...checkUrls(value, currentPath));
    }
  }

  return errors;
}

/**
 * Validate a schema object
 */
function validateSchema(schema: unknown, schemaName: string, isTopLevel = true): ValidationResult {
  const errors: ValidationError[] = [];

  if (typeof schema !== 'object' || schema === null) {
    return {
      isValid: false,
      errors: [
        {
          field: 'root',
          message: 'Schema must be an object',
        },
      ],
    };
  }

  const schemaObj = schema as Record<string, unknown>;

  // Check @context - only required for top-level schemas
  if (isTopLevel && schemaObj['@context'] !== 'https://schema.org') {
    errors.push({
      field: '@context',
      message: '@context must be "https://schema.org"',
      value: schemaObj['@context'],
    });
  }

  // Check @type
  if (!schemaObj['@type']) {
    errors.push({
      field: '@type',
      message: '@type is required',
    });
  }

  // Check for undefined/null values
  errors.push(...checkForUndefinedOrNull(schemaObj));

  // Check URLs
  errors.push(...checkUrls(schemaObj));

  return {
    isValid: errors.length === 0,
    errors,
  };
}

/**
 * Test schema generation functions
 */
async function testSchemaGeneration() {
  console.warn('🔍 Validating structured data schemas...\n');

  try {
    // Import the structured-data module
    const structuredDataModule = await import('../src/lib/structured-data.ts');
    
    // Mock beach data for testing
    const mockBeach = {
      id: 'test-beach-1',
      name: 'Test Beach',
      area: 'Crete',
      slug: 'test-beach',
      description: 'A beautiful test beach',
      photo_url: 'https://example.com/beach.jpg',
      latitude: 35.5,
      longitude: 24.0,
      organized: true,
      blue_flag: false,
      parking: 'SMALL_LOT',
      amenities: ['lifeguard', 'parking'],
      type: 'SANDY',
      wave_conditions: 'CALM',
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-12-19T00:00:00Z',
      status: 'ACTIVE' as const,
      photo_source: null,
    };

    const mockArea = {
      id: 'test-area-1',
      name: 'Crete',
      slug: 'crete',
      description: 'Test area description',
      hero_photo_url: null,
      hero_photo_source: null,
      status: 'ACTIVE' as const,
      created_at: '2024-01-01T00:00:00Z',
      updated_at: '2024-12-19T00:00:00Z',
    };

    const canonicalUrl = 'https://beachesofgreece.com/crete/test-beach';

    // Test Beach Place Schema (nested schema, doesn't need @context)
    console.warn('Testing generateBeachPlaceSchema...');
    const beachPlaceSchema = structuredDataModule.generateBeachPlaceSchema(mockBeach, canonicalUrl);
    const beachPlaceResult = validateSchema(beachPlaceSchema, 'BeachPlace', false);
    if (!beachPlaceResult.isValid) {
      console.error('❌ Beach Place Schema validation failed:');
      beachPlaceResult.errors.forEach((error) => {
        console.error(`   - ${error.field}: ${error.message}`);
      });
    } else {
      console.warn('✅ Beach Place Schema is valid');
    }

    // Test Beach WebPage Schema
    console.warn('\nTesting generateBeachWebPageSchema...');
    const beachWebPageSchema = structuredDataModule.generateBeachWebPageSchema(mockBeach, canonicalUrl);
    const beachWebPageResult = validateSchema(beachWebPageSchema, 'BeachWebPage');
    if (!beachWebPageResult.isValid) {
      console.error('❌ Beach WebPage Schema validation failed:');
      beachWebPageResult.errors.forEach((error) => {
        console.error(`   - ${error.field}: ${error.message}`);
      });
    } else {
      console.warn('✅ Beach WebPage Schema is valid');
    }

    // Test Area WebPage Schema
    console.warn('\nTesting generateAreaWebPageSchema...');
    const areaWebPageSchema = structuredDataModule.generateAreaWebPageSchema(
      mockArea,
      [mockBeach],
      'https://beachesofgreece.com/crete'
    );
    const areaWebPageResult = validateSchema(areaWebPageSchema, 'AreaWebPage');
    if (!areaWebPageResult.isValid) {
      console.error('❌ Area WebPage Schema validation failed:');
      areaWebPageResult.errors.forEach((error) => {
        console.error(`   - ${error.field}: ${error.message}`);
      });
    } else {
      console.warn('✅ Area WebPage Schema is valid');
    }

    // Test Home WebPage Schema
    console.warn('\nTesting generateHomeWebPageSchema...');
    const homeWebPageSchema = structuredDataModule.generateHomeWebPageSchema([mockBeach]);
    const homeWebPageResult = validateSchema(homeWebPageSchema, 'HomeWebPage');
    if (!homeWebPageResult.isValid) {
      console.error('❌ Home WebPage Schema validation failed:');
      homeWebPageResult.errors.forEach((error) => {
        console.error(`   - ${error.field}: ${error.message}`);
      });
    } else {
      console.warn('✅ Home WebPage Schema is valid');
    }

    // Test Map WebPage Schema
    console.warn('\nTesting generateMapWebPageSchema...');
    const mapWebPageSchema = structuredDataModule.generateMapWebPageSchema(
      [mockBeach],
      'https://beachesofgreece.com/map'
    );
    const mapWebPageResult = validateSchema(mapWebPageSchema, 'MapWebPage');
    if (!mapWebPageResult.isValid) {
      console.error('❌ Map WebPage Schema validation failed:');
      mapWebPageResult.errors.forEach((error) => {
        console.error(`   - ${error.field}: ${error.message}`);
      });
    } else {
      console.warn('✅ Map WebPage Schema is valid');
    }

    // Summary
    const allResults = [
      beachPlaceResult,
      beachWebPageResult,
      areaWebPageResult,
      homeWebPageResult,
      mapWebPageResult,
    ];
    const totalErrors = allResults.reduce((sum, result) => sum + result.errors.length, 0);
    const allValid = allResults.every((result) => result.isValid);

    console.warn('\n' + '='.repeat(50));
    if (allValid) {
      console.warn('✅ All schemas are valid!');
      process.exit(0);
    } else {
      console.error(`❌ Validation failed with ${totalErrors} error(s)`);
      process.exit(1);
    }
  } catch (error) {
    console.error('❌ Error during validation:', error);
    process.exit(1);
  }
}

// Run validation
testSchemaGeneration();

