// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnkyfxvncpawqpqccdby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhua3lmeHZuY3Bhd3FwcWNjZGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjM5MjgsImV4cCI6MjA3MzIzOTkyOH0.gi_JNT3G0i71-DQBxnI45aVXPTdU1iCjsdLFMucOXi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});